// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXrcVCwVp2sw9AmFPigWCc-BZFimTqIw8',
    appId: '1:257813727500:web:123b93775e9fae9748e129',
    messagingSenderId: '257813727500',
    projectId: 'flutterbackend-4f13d',
    authDomain: 'flutterbackend-4f13d.firebaseapp.com',
    storageBucket: 'flutterbackend-4f13d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzPmsGVB1NAXU_pzmEIeKI5UH-TOJCKs',
    appId: '1:257813727500:android:32b8929c1fe7b12c48e129',
    messagingSenderId: '257813727500',
    projectId: 'flutterbackend-4f13d',
    storageBucket: 'flutterbackend-4f13d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvSD0MCcsqRdQGPspMk_qg7g7rK_SQUCc',
    appId: '1:257813727500:ios:bdce26bc24c90ace48e129',
    messagingSenderId: '257813727500',
    projectId: 'flutterbackend-4f13d',
    storageBucket: 'flutterbackend-4f13d.firebasestorage.app',
    iosBundleId: 'com.example.gamesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvSD0MCcsqRdQGPspMk_qg7g7rK_SQUCc',
    appId: '1:257813727500:ios:bdce26bc24c90ace48e129',
    messagingSenderId: '257813727500',
    projectId: 'flutterbackend-4f13d',
    storageBucket: 'flutterbackend-4f13d.firebasestorage.app',
    iosBundleId: 'com.example.gamesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXrcVCwVp2sw9AmFPigWCc-BZFimTqIw8',
    appId: '1:257813727500:web:784fb0cdd436c31548e129',
    messagingSenderId: '257813727500',
    projectId: 'flutterbackend-4f13d',
    authDomain: 'flutterbackend-4f13d.firebaseapp.com',
    storageBucket: 'flutterbackend-4f13d.firebasestorage.app',
  );
}
